### ISSUE TITLE
`inbox` command does not identify marketplace messages or message requests

### ISSUE THREAD

**Issue by scottmconway** [scottmconway/unzuckify#1]
The calls that `get_inbox_js` makes to messenger's graphQL API does not provide information about marketplace threads or message requests. Upon further inspection, the only reference I could find to them in my browser's history was in a WebSocket communication from server to client under the URL endpoint https://edge-chat.messenger.com/chat.

Interestingly enough, the response from the server contains information about _all_ threads, including "classic" DM/group threads.

From looking at the websocket communications, the client initiates an MQTT-WS client with the following parameters:
(`u`, `s`, `d`, and `aid` have been redacted)

```json
{
    "u": "000000000000000",
    "s": 0000000000000000,
    "cp": 3,
    "ecp": 10,
    "chat_on": false,
    "fg": true,
    "d": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "ct": "websocket",
    "mqtt_sid": "",
    "aid": 000000000000000,
    "st": [],
    "pm": [],
    "dc": "",
    "no_auto_fg": true,
    "gas": null,
    "pack": [],
    "php_override": "",
    "p": null
}
```
The WS response containing thread information is a LightSpeed response with a `payload`, and looks like it'd _almost_ work if passed to `get_inbox_data`. _However_, I see a key(?) named `deleteThenInsertMessageRequest`, which `get_inbox_data` currently doesn't deal with. Unsure if it actually matters.

Next steps:
* Investigate MQTT-WS clients for python (currently eyeing [paho](https://www.eclipse.org/paho/index.php?page=clients/python/index.php))
* See if my example parsed JSON output from the websocket _just works_ with `get_inbox_data`
* Poke at the websocket endpoint until I get the response I'm looking for

**Comment by scottmconway** [comment]
@radian-software @raxod502 just FYI - the message request bit may be pertinent for your goals

**Comment by raxod502** [comment]
Interesting. Yeah, can't say I have much insight here, I kind of brute forced the reverse engineering until I got what I needed for my specific use case, in which I didn't care about message requests or marketplace messages because I was moving off the platform. I suspect that a great deal of effort will be needed to make a real client that supports the kind of absurd number of different features Facebook has shoved into their chat API.
